# Generated by Django 4.1.7 on 2023-04-15 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 15, 13, 54, 59, 59332), verbose_name='Опубликована'),
        ),
    ]
